Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -36,14 +36,22 @@ jobs:
           script: |
             if [ "$(docker ps -aq -f name=tp4scsapi)" ]; then
                 echo "Stopping tp4scsapi..."
-                docker stop tp4scsapi || true # Đảm bảo không có lỗi nếu container đã dừng
+                docker stop tp4scsapi || true
+                sleep 5  # Cho một khoảng thời gian để container dừng hoàn toàn
                 echo "Removing tp4scsapi..."
-                docker rm tp4scsapi
+                docker rm tp4scsapi || { echo "Failed to remove tp4scsapi"; exit 1; }
             else
                 echo "tp4scsapi does not exist."
             fi
-
-
+            
             docker images --filter=reference='hieu15402/tp4scsapi' --format '{{.ID}} {{.Tag}}' | grep '<none>' | awk '{print $1}' | xargs -I {} docker rmi -f {}
             docker pull hieu15402/tp4scsapi
-            docker run -d -p 8080:8080 --name tp4scsapi --restart always hieu15402/tp4scsapi
+            
+            # Kiểm tra xem cổng 8080 có sẵn hay không trước khi chạy container
+            if lsof -i :8080; then
+                echo "Port 8080 is in use, container might not start."
+                exit 1
+            fi
+            
+            docker run -d -p 8080:8080 --name tp4scsapi --restart always hieu15402/tp4scsapi || { echo "Failed to start tp4scsapi container"; exit 1; }
+
